version: "3.1"

services:
  server:
    container_name: app
    env_file:
      - .env
    ports:
      - "8080:8080"
    network_mode: bridge
    build: .
    environment:
      PORT: ${PORT}

      DB_DB: ${DB_DB}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}

      JWT_SECRET: ${JWT_SECRET}
    
    volumes:
      - app-public:/usr/src/app/public

volumes:
  app-public: